openapi: 3.0.0
info:
  version: 0.0.1
  title: Driving School Distributed Management System
  description: 'The project for the courses "Laboratory of software systems" and "Distributed Systems" '
servers:
  - description: Base URL that should be replaced with the gateway URL
    url: "http://localhost:8000/"
paths:
  "/dossiers":
    $ref: './dossierService.yaml#/~1dossiers'
  "/dossiers/{id}":
    $ref: './dossierService.yaml#/~1dossiers~1%7Bid%7D'
  "/dossiers/{id}/examStatus":
    $ref: './dossierService.yaml#/~1dossiers~1%7Bid%7D~1examStatus'
  "/doctorSlots":
    $ref: './doctorService.yaml#/~1doctorSlots'
  "/doctorSlots/{id}":
    $ref: './doctorService.yaml#/~1doctorSlots~1%7Bid%7D'
  "/drivingSlots":
    $ref: './drivingService.yaml#/~1drivingSlots'
  "/drivingSlots/{drivingSlotId}":
    $ref: './drivingService.yaml#/~1drivingSlots~1%7BdrivingSlotId%7D'
  "/practicalExamDays":
    $ref: './drivingService.yaml#/~1practicalExamDays'
  "/theoreticalExam/pass":
    $ref: './examService.yaml#/~1theoreticalExam~1pass'
  "/theoreticalExam/{id}/pass":
    $ref: './examService.yaml#/~1theoreticalExam~1%7Bid%7D~1pass'
  "/theoreticalExam/examAppeal":
    $ref: './examService.yaml#/~1theoreticalExam~1examAppeal'
  "/provisionalLicenses":
    $ref: './examService.yaml#/~1provisionalLicenses'
  "/provisionalLicenses/{id}":
    $ref: './examService.yaml#/~1provisionalLicenses~1%7Bid%7D'
  "/provisionalLicenses/{id}/validity":
    $ref: './examService.yaml#/~1provisionalLicenses~1%7Bid%7D~1validity'


components:
  schemas:
    $ref: './schemas.yaml'
  parameters:
    $ref: './parameters.yaml'
  responses:
    $ref: './responses.yaml'

