DossierId:
  name: id
  in: path
  description: id of the dossier
  required: true
  schema:
    type: string
    example: "d1"

Date:
  name: date
  in: path
  description: date for indicate which doctor slots to take
  required: true
  schema:
    type: string
    example: "2023-12-10"

DrivingSlotId:
  name: drivingSlotId
  in: path
  description: id of a driving slot
  required: true
  schema:
    type: string
    example: "fnodjdsk5bt5ofn"

ProvisionalLicenseUpdateParam:
  name: "practicalExamUpdate"
  in: query
  required: true
  schema:
    type: string
    enum: [PASSED, FAILED]
    example: [PASSED]